name: Ask OpenAI

on:
 workflow_dispatch:
   inputs:
     question:
       description: 'The question to ask OpenAI'
       required: true

jobs:
  ask_openai:
    runs-on: mylab-vm
    steps:
    - name: Ask OpenAI
      uses: openai/ask-openai@v1
      with:
        question: ${{ inputs.question }}
    - name: Print Answer
      run: echo "::notice title=Your asnwer is - ::${{ steps.ask_openai.outputs.answer }}"

