name: Ask OpenAI

on:
  push:
    branches:
      - master

jobs:
  ask_openai:
    runs-on: mylab-vm
    steps:
    - name: Ask OpenAI
      uses: openai/ask-openai@v1
      with:
        question: ${{ inputs.question }}
    - name: Print Answer
      run: echo "The answer is: ${{ steps.ask_openai.outputs.answer }}"

inputs:
  question:
    description: 'The question to ask OpenAI'
    required: true
