name: OpenAPI

on: 
  workflow_dispatch:
    inputs:
      ASK:
        default: "\"what is my ip?\""
        required: true
        description: "Ask your question in msg"
permissions:
  id-token: write 
  contents: read  
env:
  OPENAI_KEY: '${{ secrets.OPENAI_KEY }}'      
jobs:
  chatbot:
    runs-on: mylab-vm
    environment: production
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Environment setup
      run: |
        pip install openai
    - name: Run the execution
      id: msgin
      run: |
        python3 app.py ${{ github.event.inputs.ASK }}
    - name: have outputs
      id: msgoutme
      run: |
         echo "test=$(cat demo.txt)" >> $GITHUB_OUTPUT
    - name: results
      run: |
        echo "::notice title=Your Answer::${{ steps.msgoutme.outputs.test }}"
