name: Greetings

on: workflow_dispatch

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: testing env
        run: |
          echo '============================='
          printenv
          echo '=============================='
