name: Greetings

on: workflow_dispatch

jobs:
  greeting:
    runs-on: mylab-win
    permissions:
      issues: write
      pull-requests: write
    steps:
     - uses: Amadevus/pwsh-script@v2
       id: my-script
       with:
         script: '1 + 1'
     - run: echo "${{ steps.my-script.outputs.result }}"
       
