name: OpenAPI2

on: 
  workflow_dispatch:
    inputs:
      ASK:
        default: "\"what is my ip?\""
        required: true
        description: "Ask your question in msg"
permissions:
  id-token: write 
  contents: read  
env:
  OPENAI_KEY: '${{ secrets.OPENAI_KEY }}'      
jobs:
  chatbot2:
    runs-on: mylab-docker
    environment: production
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Environment setup
      run: |
        pip install openai
    - name: Run the execution
      id: msgin
      run: |
        python3 app1.py ${{ github.event.inputs.ASK }}
    - name: notice
      run: |
        echo "::notice title=Result::${{ steps.msgin.outputs.result }}"
